#!/bin/bash

# Abort script in case any command fails
set -e

# General update
sudo apt update -y
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Update and upgrade OK"

# CMAKE
sudo apt install cmake -y
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> CMake OK"

# CLANG
sudo apt install clang -y
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Clang OK"

# NUMACTL
sudo apt install numactl -y
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Numactl OK"

cd ..

# LLVM OpenMP
FILE=llvm-project/build-openmp/include/omp.h
if [[ -f "$FILE" ]];
then
    echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> LLVM already installed, skipping"
else
    git clone https://github.com/llvm/llvm-project.git
    cd llvm-project
    mkdir build-openmp
    cd build-openmp
    cmake ../openmp -G "Unix Makefiles" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release  -DOPENMP_ENABLE_LIBOMPTARGET=OFF -DLIBOMP_OMPT_OPTIONAL=ON -DCMAKE_INSTALL_PREFIX=.
    make -j16
    make install
    cd
    echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> LLVM OK"
fi

# OpenBLAS
FILE=OpenBLAS/build/include/lapacke.h
if [[ -f "$FILE" ]];
then
    echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> OpenBLAS already installed, skipping"
else
    git clone https://github.com/xianyi/OpenBLAS.git
    cd OpenBLAS
    mkdir build
    make -j 12 USE_THREAD=1 NUM_BUFFERS=512 NUM_THREADS=512 CC=clang CXX=clang++
    make PREFIX=build/ install
    cd
    echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> OpenBLAS OK"
fi

cd tpm/
