#!/bin/bash

MATRIX=(4096)
TILE=(1024)
THREADS=16
CASE=({1..1})

export TPM_PAPI_SET=0
export TPM_POWER_SET=1

ROOT=/home/xps/Work/Software
TPM=${ROOT}/TPM
CHAMELEON=${ROOT}/chameleon-tpm/build/bin

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/${ROOT}/OpenBLAS/build/lib
export OPENBLAS_NUM_THREADS=1

cd $TPM/tracelib && rm -rf CMakeFiles/ cmake_install.cmake CMakeCache.txt Makefile libTPMLibrary.so
cmake .
make -s clean && make -s
cd -
cd $TPM/power && rm -rf CMakeFiles/ cmake_install.cmake CMakeCache.txt Makefile TPMpower
cmake .
make -s clean && make -s
cd -

TRACELIB_PRELOAD=${TPM}/tracelib/libTPMLibrary.so

if [ $TPM_PAPI_SET -eq 1 ];
then
    THREADS=1
fi

while IFS= read -r algorithm
do
    for matrix in ${MATRIX[*]}
    do
        for tile in ${TILE[*]}
        do
            for case in ${CASE[*]}
            do
                export TPM_ALGORITHM=$algorithm
        
                lowest_freq=$(cpufreq-info -l | awk '{print $1}')
                default_freq=$(cpufreq-info -l | awk '{print $2}')
                sudo -E ${TPM}/power/TPMpower $algorithm $THREADS $case $lowest_freq $default_freq &
                echo "TPM BASH power server launched"
                
                echo "TPM BASH tracelib launching" $algorithm "case" $case "with parameters" $THREADS $matrix $tile
                LD_PRELOAD=$OPENMP_PRELOAD:$TRACELIB_PRELOAD numactl --physcpubind=0-$(expr $THREADS - 1) --membind=0 ${CHAMELEON}/chameleon_dtesting -w -o $algorithm -t $THREADS -m $matrix -n $matrix -k $matrix -b $tile -i $tile
                echo "TPM BASH tracelib done" $algorithm "case" $case "with parameters" $THREADS $matrix $tile
            done
        done
    done
done < benchmarks/benchmarks2.txt

ps -ef | grep TPMpower | grep -v grep | awk '{print $2}' | sudo xargs -r kill -9