#!/bin/bash

# E5-2670 v3 with hyperthreading enabled

machine=haswell
threads=48
numa=24

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/cc/OpenBLAS/build/lib

source launch_script qr 16384 1024 24 24 haswell min
source launch_script qr 16384 1024 48 24 haswell min

source launch_script qr 16384 2048 24 24 haswell min
source launch_script qr 16384 2048 48 24 haswell min

source launch_script qr 32768 1024 24 24 haswell min
source launch_script qr 32768 1024 48 24 haswell min

source launch_script qr 32768 2048 24 24 haswell min
source launch_script qr 32768 2048 48 24 haswell min

source launch_script cholesky 16384 1024 24 24 haswell min
source launch_script cholesky 16384 1024 48 24 haswell min

source launch_script cholesky 16384 2048 24 24 haswell min
source launch_script cholesky 16384 2048 48 24 haswell min

source launch_script cholesky 32768 1024 24 24 haswell min
source launch_script cholesky 32768 1024 48 24 haswell min

source launch_script cholesky 32768 2048 24 24 haswell min
source launch_script cholesky 32768 2048 48 24 haswell min

source launch_script lu 16384 1024 24 24 haswell min
source launch_script lu 16384 1024 48 24 haswell min

source launch_script lu 16384 2048 24 24 haswell min
source launch_script lu 16384 2048 48 24 haswell min

source launch_script lu 32768 1024 24 24 haswell min
source launch_script lu 32768 1024 48 24 haswell min

source launch_script lu 32768 2048 24 24 haswell min
source launch_script lu 32768 2048 48 24 haswell min

source launch_script sparselu 512 256 24 24 haswell min
source launch_script sparselu 512 256 48 24 haswell min


